# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6d00f2f01f0b2256c67571603697af079d9dd57b51cae5b4e859d3012f476c324a5c20d0ef49982519dfc0c018358a53e16fe7a1594435616c5975b988d915e

test:
  secret_key_base: 4c5fa11fed9d6ea1c7a9f8c8459dd63099d9e7244307049762caa33bd46b81c1c49cc5f60b06ab8bf293fbb378cef9031157be2eac0cc2532c567f6eeaaf55c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
